package grammar;

import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.RuleContext;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeListener;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import sound.Song;
import grammar.ABCMusicHeaderLexer;
import grammar.ABCMusicHeaderParser;

public class MusicPlayerBody {
	private Song song;
	
	/** 
	 * @param inputSong Song created by HeaderListener
	 */
	public MusicPlayerBody(Song inputSong) {
		super();
		this.song = inputSong;
	}
	
	/**  
	 * @param songString String representation of song body
	 * @return Song object generated by parsing fields of songString
	 */
	public Song parse(String songString) {
    	try{
    		BodyListener listener = runListener(songString);
    		return listener.getSong();
    	}
    	catch(Exception e){
    		throw new RuntimeException("Invalid Body Input!");
    	}
    }
	
	/**
	 * @param input String representation of song
	 * @return BodyListener used to walk along body's parse tree
	 */
    public BodyListener runListener(String input) {
        // Create a stream of tokens using the lexer ABCMusicBodyLexer.
        CharStream stream = new ANTLRInputStream(input);
        ABCMusicBodyLexer lexer = new ABCMusicBodyLexer(stream);
        lexer.reportErrorsAsExceptions();
        TokenStream tokens = new CommonTokenStream(lexer);
        
        // Feed the tokens into the parser.
        ABCMusicBodyParser parser = new ABCMusicBodyParser(tokens);
        parser.reportErrorsAsExceptions();
        
        // Generate the parse tree using the starter rule.
        ParseTree tree;
        tree = parser.abc_tune_body(); // "abc_tune_body" is the starter rule.

        // debugging option #1: print the tree to the console
        // System.err.println(tree.toStringTree(parser));

        // debugging option #2: show the tree in a window
        // ((RuleContext)tree).inspect(parser);

        // Walk the tree with the listener.
        ParseTreeWalker walker = new ParseTreeWalker();
        ParseTreeListener listener = new BodyListener(this.song);
        walker.walk(listener, tree);
      
        BodyListener bodylistener = (BodyListener) listener;
        return bodylistener;
    }
    
}